# Generated by Django 4.2.1 on 2023-05-15 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20190410_2136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
