# Generated by Django 4.2.1 on 2023-05-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_alter_leave_defaultdays_alter_leave_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='defaultdays',
            field=models.PositiveIntegerField(blank=True, default=50, null=True, verbose_name='Количество дней отпуска в год счетчик'),
        ),
    ]
