# Generated by Django 4.2.1 on 2023-05-18 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_alter_leave_defaultdays'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
