# Generated by Django 4.2.1 on 2023-05-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_terminated',
            field=models.BooleanField(default=False),
        ),
    ]
