# Generated by Django 4.2.1 on 2023-05-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_militaryrecord_created_militaryrecord_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='work_schedule',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='График работы'),
        ),
    ]
