# Generated by Django 4.2.1 on 2023-05-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_bank_work_schedule_alter_schedule_work_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='work_schedule',
            field=models.CharField(blank=True, choices=[(1, '8 часов в день (40 в неделю)'), (2, '2,5 часа в день (четыре раза в неделю)'), (3, '8-часов в день, 8-часов в ночь (40 часов в неделю)'), (4, '8-часов в день с выходными')], max_length=100, null=True, verbose_name='График работы'),
        ),
    ]
