# Generated by Django 4.2.1 on 2023-05-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_bank_work_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holiday',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='WorkSchedule',
        ),
    ]
