# Generated by Django 4.2.1 on 2023-05-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_bank_work_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leavetype',
            field=models.CharField(choices=[('ежегодный основной оплачиваемый отпуск', 'ежегодный основной оплачиваемый отпуск'), ('ежегодный дополнительный оплачиваемый отпуск', 'ежегодный дополнительный оплачиваемый отпуск'), ('отпуск без сохранения заработной платы', 'отпуск без сохранения заработной платы'), ('учебный отпуск', 'учебный отпуск'), ('отпуск по беременности и родам', 'отпуск по беременности и родам'), ('другой', 'другой')], default='ежегодный основной оплачиваемый отпуск', max_length=44, null=True, verbose_name='Тип отпуска'),
        ),
    ]
