# Generated by Django 4.2.1 on 2023-05-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_alter_leave_leavetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='work_schedule',
            field=models.IntegerField(blank=True, choices=[(1, '8 часов в день (40 в неделю)'), (2, '2,5 часа в день (четыре раза в неделю)'), (3, '2 дня рабочих 2 выходных')], null=True, verbose_name='График работы'),
        ),
    ]
