# Generated by Django 4.2.1 on 2023-05-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_bank_work_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата праздника')),
                ('name', models.CharField(max_length=100, verbose_name='Название праздника')),
            ],
        ),
    ]
