# Generated by Django 4.2.1 on 2023-06-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='experience_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='bank',
            name='experience_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='bank',
            name='labor_book_in_possession',
            field=models.BooleanField(default=False, verbose_name='Трудовая книжка на руках'),
        ),
        migrations.AddField(
            model_name='bank',
            name='labor_book_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи трудовой книжки'),
        ),
        migrations.AddField(
            model_name='bank',
            name='labor_book_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер трудовой книжки'),
        ),
        migrations.AddField(
            model_name='bank',
            name='labor_book_series',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Серия трудовой книжки'),
        ),
        migrations.AddField(
            model_name='bank',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='bank',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
    ]
