# Generated by Django 4.2.1 on 2023-06-03 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_remove_bank_experience_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('experience_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Организация')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
