# Generated by Django 4.2.1 on 2023-06-04 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_employmenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='lastwork',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
    ]
