# Generated by Django 4.2.1 on 2023-06-09 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_remove_employee_lastwork_remove_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='SickLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('diagnosis', models.CharField(max_length=255, verbose_name='Диагноз')),
                ('conclusion', models.CharField(max_length=255, verbose_name='Заключение')),
                ('issuing_institution', models.CharField(max_length=255, verbose_name='Учреждение выдавшее справку')),
                ('doctor_name', models.CharField(max_length=255, verbose_name='ФИО врача')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
