# Generated by Django 4.2.1 on 2023-06-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_sickleave_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='nextofkin',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='relationship',
        ),
    ]
