# Generated by Django 4.2.1 on 2023-05-15 22:22

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0037_alter_employee_sex_alter_employee_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='relationship',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Sister', 'Sister'), ('Brother', 'Brother'), ('Uncle', 'Uncle'), ('Aunty', 'Aunty'), ('Husband', 'Husband'), ('Wife', 'Wife'), ('Fiance', 'Fiance'), ('Cousin', 'Cousin'), ('Fiancee', 'Fiancee'), ('Niece', 'Niece'), ('Nephew', 'Nephew'), ('Son', 'Son'), ('Daughter', 'Daughter')], default='Father', help_text='Who is this person to you ?', max_length=40, null=True, verbose_name='Relationship with Person'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, help_text='Адрес текущего места жительства', max_length=125, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bio',
            field=models.CharField(blank=True, default='', help_text='Дополнительная информация', max_length=255, null=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Созданно'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dateissued',
            field=models.DateField(help_text='Дата выдачи пропуска', null=True, verbose_name='Дата выдачи пропуска'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.department', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(choices=[('Начальное профессиональное образование', 'Основное общее образование'), ('Неполное высшее образование', 'Среднее общее образование'), ('Среднее профессиональное образование', 'Среднее профессиональное образование'), ('Основное общее образование', 'Высшее образование'), ('Начальное (общее) образование', 'Начальное общее образование'), ('Послевузовское образование', 'Другое')], default='Начальное профессиональное образование', help_text='Уровень образования', max_length=38, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeid',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Табельный номер сотрудника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeetype',
            field=models.CharField(choices=[('Полный рабочий день', 'Полный рабочий день'), ('Неполный рабочий день', 'Неполный рабочий день'), ('Договор', 'Договор'), ('Стажер', 'Стажер')], default='Полный рабочий день', max_length=21, null=True, verbose_name='Тип сотрудника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(max_length=125, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hometown',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(blank=True, default='default.png', help_text='upload image size less than 2.0MB', null=True, upload_to='profiles', verbose_name='Изображение профиля'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastname',
            field=models.CharField(max_length=125, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastwork',
            field=models.CharField(blank=True, help_text='Где вы работали в последний раз?', max_length=125, null=True, verbose_name='Последнее место работы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.nationality', verbose_name='Национальность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='othername',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, help_text='Какую должность вы занимали на последнем месте работы?', max_length=255, null=True, verbose_name='Занимаемая должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='region',
            field=models.CharField(choices=[('Ahafo', 'Ahafo'), ('Ashanti', 'Ashanti'), ('Bono East', 'Bono East'), ('Bono', 'Bono'), ('Central', 'Central'), ('Eastern', 'Eastern'), ('Greater Accra', 'Greater Accra'), ('North East', 'Northen East'), ('Northen', 'Northen'), ('Oti', 'Oti'), ('Savannah', 'Savannah'), ('Upper East', 'Upper East'), ('Upper West', 'Upper West'), ('Volta', 'Volta'), ('Western North', 'Western North'), ('Western', 'Western')], default='Greater Accra', help_text='Из какого региона страны вы родом?', max_length=20, null=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='religion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.religion', verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='residence',
            field=models.CharField(max_length=125, verbose_name='Текущее место жительства'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.role', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский'), ('other', 'Other'), ('Not Known', 'Not Known')], default='Мужской', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='startdate',
            field=models.DateField(help_text='Дата приема на работу', null=True, verbose_name='Дата приема на работу'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+7900000000', help_text='Введите номер с кодом страны', max_length=128, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tinnumber',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Mss', 'Mss'), ('Dr', 'Dr'), ('Sir', 'Sir'), ('Madam', 'Madam')], default='Mr', max_length=5, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='children',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Кол-во детей'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Номер телефона ближайшего родственника', max_length=128, null=True, region=None, verbose_name='Номер телефона ближайшего родственника'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='father',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя отца'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='foccupation',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Профессия отца'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='moccupation',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Профессия матери'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='mother',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя матери'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='nextofkin',
            field=models.CharField(help_text='ФИО ближайшего родственника', max_length=255, null=True, verbose_name='Ближайшие родственники'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='occupation',
            field=models.CharField(blank=True, help_text='род занятий супруга\\ги', max_length=125, null=True, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship',
            field=models.CharField(choices=[('Отец', 'Отец'), ('Мать', 'Мать'), ('Сестра', 'Сестра'), ('Брат', 'Брат'), ('Дядя', 'Дядя'), ('Тётя', 'Тетя'), ('Муж', 'Муж'), ('Жена', 'Жена'), ('Жених', 'Жених'), ('Cousin', 'Cousin'), ('Жена', 'Невеста'), ('Племянница', 'Племянница'), ('Племянник', 'Племянник'), ('Сын', 'Сын'), ('Дочь', 'Дочь')], help_text='Кем для вас является этот человек?', max_length=40, null=True, verbose_name='Отношения с ближайшим родственником'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='spouse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Супруг\\а (ФИО)'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('Состоит в зарегистрированном браке ', 'В браке'), ('Никогда не состоял(не состояла) в браке ', 'Одинок(а)'), ('В разводе', 'В разводе'), ('Вдова', 'Вдова'), ('Вдовец', 'Вдовец')], default='Никогда не состоял(не состояла) в браке ', max_length=40, null=True, verbose_name='Семейное положение'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, help_text='Введите номер с кодом страны', max_length=128, null=True, region=None, verbose_name='Номер телефона супруга\\ги'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено'),
        ),
    ]
