# Generated by Django 4.2.1 on 2023-05-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0038_alter_emergency_relationship_alter_employee_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='region',
            field=models.CharField(choices=[('Ahafo', 'Ahafo'), ('Ashanti', 'Ashanti'), ('Bono East', 'Bono East'), ('Bono', 'Bono'), ('Central', 'Central'), ('Eastern', 'Eastern'), ('Greater Accra', 'Greater Accra'), ('North East', 'Northen East'), ('Northen', 'Northen'), ('Oti', 'Oti'), ('Savannah', 'Savannah'), ('Upper East', 'Upper East'), ('Upper West', 'Upper West'), ('Volta', 'Volta'), ('Western North', 'Western North'), ('Western', 'Western')], default='Greater Accra', max_length=20, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default='Мужской', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ssnitnumber',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='startdate',
            field=models.DateField(help_text='Дата по приказу', null=True, verbose_name='Дата приема на работу'),
        ),
    ]
