# Generated by Django 4.2.1 on 2023-05-15 22:53

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0039_alter_employee_region_alter_employee_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account',
            field=models.CharField(help_text='Номер счета сотрудника', max_length=30, null=True, verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='branch',
            field=models.CharField(blank=True, help_text='В каком отделении был открыт счет', max_length=125, null=True, verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='employee',
            field=models.ForeignKey(help_text='Выберите сотрудника(ов) для добавления банковского счета', null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=125, null=True, verbose_name='Наименование банка'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Оклад'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='fullname',
            field=models.CharField(help_text='С кем мы должны связаться?', max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='location',
            field=models.CharField(max_length=125, null=True, verbose_name='Место жительства'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='relationship',
            field=models.CharField(choices=[('Отец', 'Отец'), ('Мать', 'Мать'), ('Сестра', 'Сестра'), ('Брат', 'Брат'), ('Дядя', 'Дядя'), ('Тетя', 'Тетя'), ('Муж', 'Муж'), ('Жена', 'Жена'), ('Сын', 'Сын'), ('Дочь', 'Дочь')], default='Отец', help_text='Кто этот человек для вас?', max_length=40, null=True, verbose_name='Отношения с человеком'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+7900000000', help_text='Введите номер с кодом страны', max_length=128, region=None, verbose_name='Номер телефона'),
        ),
    ]
