# Generated by Django 4.2.1 on 2023-05-15 22:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0040_alter_bank_account_alter_bank_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+79', help_text='Введите номер с кодом страны', max_length=128, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+79', help_text='Введите номер с кодом страны', max_length=128, region=None, verbose_name='Номер телефона'),
        ),
    ]
