# Generated by Django 4.2.1 on 2023-05-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0041_alter_emergency_tel_alter_employee_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Date_issue',
            field=models.DateField(null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Document_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер документа'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Document_series',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Серия документа'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Issued',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Subdivision_ID',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Серия документа'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(blank=True, default='default.png', help_text='Загружайте изображения размером менее 2,0 МБ', null=True, upload_to='profiles', verbose_name='Изображение профиля'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(choices=[('Военный билет', 'Военный билет'), ('Паспорт', 'Паспорт'), ('Свидетельство о рождении', 'Свидетельство о рождении')], default='Паспорт', max_length=24, null=True, verbose_name='Вид документа'),
        ),
    ]
