# Generated by Django 4.2.1 on 2023-05-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0042_employee_date_issue_employee_document_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='region',
        ),
        migrations.AddField(
            model_name='employee',
            name='Apartment',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Corps',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Корпус'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Date_Registrations',
            field=models.DateField(null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AddField(
            model_name='employee',
            name='District',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Home',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Resolution',
            field=models.CharField(blank=True, help_text='Разрешение на работу иностранного сотрудника', max_length=125, null=True, verbose_name='Разрешение на работу №'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Settlement',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Населенный пункт'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Street',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Unit_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Код подразделения '),
        ),
        migrations.AddField(
            model_name='employee',
            name='Zip_Code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Почтовый индекс '),
        ),
        migrations.AddField(
            model_name='employee',
            name='Region',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Область'),
        ),
    ]
