# Generated by Django 4.2.1 on 2023-05-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0044_alter_employee_lastwork_alter_employee_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Subdivision_ID',
        ),
        migrations.AlterField(
            model_name='employee',
            name='Date_issue',
            field=models.DateField(null=True, verbose_name='Дата выдачи (YYYY-mm-dd)'),
        ),
    ]
