# Generated by Django 4.2.1 on 2023-05-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0045_remove_employee_subdivision_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Apartment',
            field=models.CharField(blank=True, default='кв.', max_length=125, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Corps',
            field=models.CharField(blank=True, default='корп.', max_length=125, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Home',
            field=models.CharField(blank=True, default='д.', max_length=125, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Street',
            field=models.CharField(blank=True, default='ул.', max_length=125, null=True, verbose_name='Улица'),
        ),
    ]
