# Generated by Django 4.2.1 on 2023-05-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0048_alter_employee_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Apartment',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(blank=True, default='default.png', help_text='Загрузи изображения не более 2.0 Мб', null=True, upload_to='profiles', verbose_name='Изображение профиля'),
        ),
    ]
