# Generated by Django 4.2.1 on 2023-05-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0053_alter_relationship_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='father',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='foccupation',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='moccupation',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='mother',
        ),
        migrations.AlterField(
            model_name='relationship',
            name='nextofkin',
            field=models.CharField(help_text='ФИО', max_length=255, null=True, verbose_name='Ближайшие родственники'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship',
            field=models.CharField(choices=[('Отец', 'Отец'), ('Мать', 'Мать'), ('Сестра', 'Сестра'), ('Брат', 'Брат'), ('Дядя', 'Дядя'), ('Тётя', 'Тетя'), ('Муж', 'Муж'), ('Жена', 'Жена'), ('Жених', 'Жених'), ('Cousin', 'Cousin'), ('Жена', 'Невеста'), ('Племянница', 'Племянница'), ('Племянник', 'Племянник'), ('Сын', 'Сын'), ('Дочь', 'Дочь')], help_text='Кем для вас является этот человек?', max_length=40, null=True, verbose_name='Родственные связи '),
        ),
    ]
