# Generated by Django 4.2.1 on 2023-05-17 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0054_remove_relationship_father_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='contact',
        ),
        migrations.AlterField(
            model_name='relationship',
            name='nextofkin',
            field=models.CharField(help_text='ФИО', max_length=255, null=True, verbose_name='Ближайший родственник'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Файл документа')),
                ('filename', models.CharField(max_length=255, verbose_name='Название файла')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
