# Generated by Django 4.2.1 on 2023-05-18 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0056_document_created_document_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employee.employee', verbose_name='Сотрудник'),
        ),
    ]
