# Generated by Django 4.2.1 on 2023-05-18 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0058_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Сотрудник'),
        ),
    ]
