# Generated by Django 4.2.1 on 2023-05-18 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0059_alter_leave_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='user',
            new_name='employee',
        ),
    ]
