# Generated by Django 4.2.1 on 2023-05-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0060_rename_user_leave_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leavetype',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('emergency', 'Emergency Leave'), ('study', 'Study Leave')], default='sick', max_length=25, null=True, verbose_name='Тип отпуска'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.CharField(blank=True, help_text='Добавить дополнительную информацию для отпуска', max_length=255, null=True, verbose_name='Примечание'),
        ),
    ]
