# Generated by Django 4.2.1 on 2023-05-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0061_alter_leave_leavetype_alter_leave_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование организации')),
                ('leader_lastname', models.CharField(max_length=100, verbose_name='Фамилия руководителя')),
                ('leader_name', models.CharField(max_length=100, verbose_name='Имя руководителя')),
                ('leader_namemiddle', models.CharField(max_length=100, verbose_name='Отчество руководителя')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.AlterField(
            model_name='leave',
            name='defaultdays',
            field=models.PositiveIntegerField(blank=True, default=140, null=True, verbose_name='Количество дней отпуска в год счетчик'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leavetype',
            field=models.CharField(choices=[('sick', 'ежегодный основной оплачиваемый отпуск'), ('casual', 'ежегодный дополнительный оплачиваемый отпуск'), ('emergency', 'отпуск без сохранения заработной платы'), ('study', 'учебный отпуск'), ('birth', 'отпуск по беременности и родам'), ('other', 'другой')], default='sick', max_length=25, null=True, verbose_name='Тип отпуска'),
        ),
    ]
